name: CI
on: [push]
jobs:
  theme-check:
    name: Theme Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Theme Check
        uses: andershagbard/theme-check-action@fix-annotations
        with:
          token: ${{ github.token }}
