name: CI
on: [push]
jobs:
  theme-check:
    name: Theme Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Theme Check
        uses: alok-test-org/theme-check-action@main
        with:
          token: ${{ github.token }}
          theme_root: ./theme
